config/routes.rb
Rails.application.routes.draw do
  # Define the controller to use to respond to the root url
  root 'static_pages#home'
  # Define some statics routes and some redirects to avoid mispellings
  get '/home', to: redirect('/')
  get '/podcast', to: 'static_pages#podcast'
  get '/team', to: 'static_pages#team'
  get '/teams', to: redirect('/team')
  get '/support', to: 'static_pages#support'
  get '/supports', to: redirect('/team')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def podcast
  end

  def team
  end

  def support
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    C_TITLE = "L'Ampli : vos podcasts et émissions sur la Musique."

    def create_title(title = '') 
        if title.nil? || title.empty?
            C_TITLE
        else
            "#{title} | #{C_TITLE}"
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<%# We doing that for not destroing this code %>
<% if false %>
<header>
  <div class="litle-screen">
    <div class="header-logo-contain">
      <%= link_to root_path do %>
        <%= image_tag image_url('lampli.png'), alt: "icons", class: "header-logo-img" %>
        <p>L'ampli</p>
      <% end %>
    </div>

    <div class="open-big-header">
      <%= image_tag image_url('Hamburger.svg'), alt: "hamburger", class: "open-header-img" %>
    </div>
  </div>

  <div class="big-screen">
    <nav class="header-nav">
      <ul class="header-list">
        <li><% if current_page?(controller: "static_pages", action: "home") %><%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %><% end %><%= link_to "Accueil", root_path %></li>
        <li><% if current_page?(controller: "static_pages", action: "podcast") %> <%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %><% end %><%= link_to "Podcasts", podcast_path %></li>
        <li><% if current_page?(controller: "static_pages", action: "team") %> <%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %><% end %><%= link_to "L'équipe", team_path %></li>
        <li><% if current_page?(controller: "static_pages", action: "support") %><%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %> <% end %><%= link_to "Nous Soutenir", support_path %></li>
      </ul>
    </nav>
  </div>

  <div class="big-header hidden">
    <div class="header-modal-top">
      <div class="header-logo-contain">
        <%= link_to root_path do %>
          <%= image_tag image_url('lampli.png'), alt: "icons", class: "header-logo-img" %>
          <p>L'ampli</p>
        <% end %>
      </div>

      <div class="close-big-header">
        <%= image_tag image_url('Close.svg'), alt: "hamburger", class: "close-header-img" %>
      </div>
    </div>

    <nav class="header-nav">
      <ul class="header-list">
        <li><% if current_page?(controller: "static_pages", action: "home") %><%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %><% end %><%= link_to "Accueil", root_path %></li>
        <li><% if current_page?(controller: "static_pages", action: "podcast") %> <%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %><% end %><%= link_to "Podcasts", podcast_path %></li>
        <li><% if current_page?(controller: "static_pages", action: "team") %> <%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %><% end %><%= link_to "L'équipe", team_path %></li>
        <li><% if current_page?(controller: "static_pages", action: "support") %><%= image_tag image_url('sound-waves.svg'), alt: "icons", class: "current-path-img" %> <% end %><%= link_to "Nous Soutenir", support_path %></li>
      </ul>
    </nav>
  </div>
</header>
<% end %>

<header>
  <div class="row-1">
    <%= link_to root_path do %>
      <%= image_tag image_url('lampli_logo/lampli_logo_white_nt.svg'), atl: "logo", class: "header-logo-img" %>
      <p>L'Ampli</p>
    <% end %>
  </div>

  <div class="row-2">
    <p>3 amis, 3 micros et quelques podcasts</p>
  </div>
</header>

app/views/layouts/_soon.html.erb
<p class="soon">Nous sommes en train de construire cette partie en ce moment, à très vite !</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  CGI.unescapeHTML create_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_cover.html.erb
<a class="cover" href="<%= link %>" target="_blank" >
    <%= image_tag image_url(cover_url), alt: 'cover', class: "cover-img" %>
    <div class="disc">
        <%= image_tag image_url(disc_url), alt: 'disc', class: "disc-img" %>
    </div>
</a>

app/views/shared/_title.html.erb
<div class="title">
    <%= image_tag image_url("jack_white.svg"), alt: 'jack', class: 'jack' %>
    <p><%= title || "" %></p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Accueil") %>
<% if false %>
<div class="home-container">
<section class="first-section">
    <div class="img-container">
        <%= image_tag image_url('lampli.png'), alt: "icons", class: "home-first-container" %>
    </div>

    <div class="accroch-container">
    <div class="text-container">
        <h1 class="title">Un Talk Show sur la musique</h1>
        <p class="subtitle">Retrouvez chaque mois un podcast sur la musique et son environment</p>
    </div>

    <div class="cta-container">
        <%= link_to podcast_path do %>
        <button>Découvrir les émissions</button>
        <% end %>
    </div>
    </div>

</section>
</div>
<% end %>

<div class="home-container">
    <section class="one-section">
        <%= render partial: 'shared/title', locals: {title: "Écoutez nos émissions :"} %>
        <div class="all-cover">
            <%= render partial: 'shared/cover', locals: {link: "https://open.spotify.com/user/jkkoqrvex50c5067bb9yz5cma", cover_url: "Vinyle/Spotify_Cover.svg", disc_url: "Vinyle/Spotify_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://anchor.fm/lampli", cover_url: "Vinyle/Anchor_Cover.svg", disc_url: "Vinyle/Anchor_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://www.youtube.com/channel/UCZge9ra1LDY32WvMxbEUBtw", cover_url: "Vinyle/Youtube_Cover.svg", disc_url: "Vinyle/Youtube_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://www.twitch.tv/lampli_studio", cover_url: "Vinyle/Twitch_Cover.svg", disc_url: "Vinyle/Twitch_Disc.svg"} %>
        </div>
    </section>
    <section class="one-section">
        <%= render partial: 'shared/title', locals: {title: "Suivez nous sur les réseaux sociaux :"} %>
        <div class="all-cover">
            <%= render partial: 'shared/cover', locals: {link: "https://www.facebook.com/lamplistudio", cover_url: "Vinyle/Facebook_Cover.svg", disc_url: "Vinyle/Facebook_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://www.instagram.com/lampli_studio/", cover_url: "Vinyle/Instagram_Cover.svg", disc_url: "Vinyle/Instagram_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://www.tiktok.com/@lampli_studio", cover_url: "Vinyle/Tiktok_Cover.svg", disc_url: "Vinyle/Tiktok_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://twitter.com/lampli_studio", cover_url: "Vinyle/Twitter_Cover.svg", disc_url: "Vinyle/Twitter_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://www.linkedin.com/in/l-ampli-studio-9b065121b/", cover_url: "Vinyle/Linkedin_Cover.svg", disc_url: "Vinyle/Linkedin_Disc.svg"} %>
        </div>
    </section>
    <section class="one-section">
        <%= render partial: 'shared/title', locals: {title: "Soutenez L'Ampli à travers un don :"} %>
        <div class="all-cover">
            <%= render partial: 'shared/cover', locals: {link: "https://paypal.me/lamplistudio", cover_url: "Vinyle/Paypal_Cover.svg", disc_url: "Vinyle/Paypal_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://utip.io/lampli", cover_url: "Vinyle/Utip_Cover.svg", disc_url: "Vinyle/Utip_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://fr.tipeee.com/lampli", cover_url: "Vinyle/Tipeee_Cover.svg", disc_url: "Vinyle/Tipeee_Disc.svg"} %>
        </div>
    </section>
    <section class="one-section">
        <%= render partial: 'shared/title', locals: {title: "Soutenez L'Ampli en achetant des vêtements et goodies L'Ampli :"} %>
        <div class="all-cover">
            <%= render partial: 'shared/cover', locals: {link: "https://lampli.myspreadshop.fr/", cover_url: "Vinyle/Spreadshirt_Cover.svg", disc_url: "Vinyle/Spreadshirt_Disc.svg"} %>
            <%= render partial: 'shared/cover', locals: {link: "https://www.redbubble.com/fr/people/Lampli/shop?asc=u", cover_url: "Vinyle/Redbubble_Cover.svg", disc_url: "Vinyle/Redbubble_Disc.svg"} %>
        </div>
    </section>
    <section class="one-section">
        <%= render partial: 'shared/title', locals: {title: "Contactez L'Ampli :"} %>
        <div class="all-cover">
            <%= render partial: 'shared/cover', locals: {link: "mailto:contact@lampli.studio", cover_url: "Vinyle/Email_Cover.svg", disc_url: "Vinyle/Email_Disc.svg"} %>
        </div>
    </section>
</div> 

app/views/static_pages/podcast.html.erb
<% provide(:title, "Podcasts") %>

    <%= render 'layouts/soon' %>

app/views/static_pages/support.html.erb
<% provide(:title, "Support") %>

    <%= render 'layouts/soon' %>

app/views/static_pages/team.html.erb
<% provide(:title,"L'équipe") %>

    <%= render 'layouts/soon' %>